#!/bin/bash

dir=$1

: '
if [[ -n $dir ]]
then
    echo $dir
    ls $dir
    for f in $(ls $dir)
    do
        echo "$dir/$f"
        if [[ -s "$dir/$f" ]] 
        then
            cat "$dir/$f"
        fi
    done
fi
'

if ! [[ -n $dir ]]
then
    exit 1
fi

cd $dir
